Repository OpenZeppelin/stellar-contracts, pull requests merged in 2025-02, with the labels that each got.

#51 `update` inline docs & readme wording
  README.md
  contracts/token/fungible/src/storage.rs
Labels: documentation

#66 readme update for open source project requirements
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Cargo.lock
  README.md
Labels: documentation

#49 [L-05] Input validation in `spend_allowance`
  contracts/token/fungible/src/storage.rs
  contracts/token/fungible/src/test.rs
  contracts/token/fungible/test_snapshots/test/spend_allowance_invalid_amount_fails.1.json
Labels: audit

#31 [CR-01] Put necessary derives for the contract errors
  contracts/token/fungible/src/fungible.rs
  contracts/utils/pausable/src/pausable.rs
  examples/fungible-pausable/src/contract.rs
  examples/fungible-token-interface/src/contract.rs
  examples/pausable/src/contract.rs
Labels: audit

#32 error code convention
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#54 [N-04] Unclear Revert Reason
  Cargo.lock
  contracts/token/fungible/src/extensions/metadata/storage.rs
  contracts/token/fungible/src/extensions/metadata/test.rs
  contracts/token/fungible/src/fungible.rs
Labels: audit

#56 [N-02] Potentially Unused Variable
  contracts/token/fungible/src/storage.rs
Labels: audit

#57 [M-01] Approval Periods Are Implicitly Restricted
  contracts/token/fungible/src/storage.rs
  contracts/token/fungible/src/test.rs
  contracts/token/fungible/test_snapshots/test/set_allowance_with_greater_than_max_ledger_fails.1.json
Labels: audit

#29 [H-01] Retaining other macros
  contracts/utils/pausable-macros/src/helper.rs
  contracts/utils/pausable-macros/src/lib.rs
Labels: audit

#62 [L-04] Instance TTL Not Updated on All Operations
  contracts/token/fungible/src/extensions/metadata/storage.rs
  contracts/token/fungible/src/lib.rs
  contracts/token/fungible/src/storage.rs
  contracts/token/fungible/src/test.rs
  contracts/token/fungible/test_snapshots/extensions/burnable/test/burn_with_allowance_works.1.json
  contracts/token/fungible/test_snapshots/extensions/burnable/test/burn_with_insufficient_allowance_panics.1.json
  contracts/token/fungible/test_snapshots/extensions/burnable/test/burn_with_insufficient_balance_panics.1.json
  contracts/token/fungible/test_snapshots/extensions/burnable/test/burn_with_no_allowance_panics.1.json
  contracts/token/fungible/test_snapshots/extensions/burnable/test/burn_works.1.json
  contracts/token/fungible/test_snapshots/extensions/metadata/test/metadata_update.1.json
  contracts/token/fungible/test_snapshots/extensions/metadata/test/set_and_get_metadata.1.json
  contracts/token/fungible/test_snapshots/extensions/mintable/test/mint_works.1.json
  contracts/token/fungible/test_snapshots/test/approve_and_transfer_from.1.json
  contracts/token/fungible/test_snapshots/test/extend_balance_ttl_thru_transfer.1.json
  contracts/token/fungible/test_snapshots/test/initial_state.1.json
  contracts/token/fungible/test_snapshots/test/transfer_from_insufficient_allowance_fails.1.json
  contracts/token/fungible/test_snapshots/test/transfer_insufficient_balance_fails.1.json
  contracts/token/fungible/test_snapshots/test/transfer_works.1.json
  contracts/token/fungible/test_snapshots/test/update_burns_tokens.1.json
  contracts/token/fungible/test_snapshots/test/update_mints_tokens.1.json
  contracts/token/fungible/test_snapshots/test/update_overflow_panics.1.json
  contracts/token/fungible/test_snapshots/test/update_transfers_between_accounts.1.json
  contracts/token/fungible/test_snapshots/test/update_with_insufficient_balance_panics.1.json
  contracts/utils/pausable/src/lib.rs
  contracts/utils/pausable/src/storage.rs
  contracts/utils/pausable/test_snapshots/test/errors_pause_when_paused.1.json
  contracts/utils/pausable/test_snapshots/test/errors_unpause_when_not_paused.1.json
  contracts/utils/pausable/test_snapshots/test/initial_state.1.json
  contracts/utils/pausable/test_snapshots/test/pause_works.1.json
  contracts/utils/pausable/test_snapshots/test/unpause_works.1.json
  contracts/utils/pausable/test_snapshots/test/when_not_paused_works.1.json
  contracts/utils/pausable/test_snapshots/test/when_paused_works.1.json
  examples/fungible-pausable/test_snapshots/test/burn_fails_when_paused.1.json
  examples/fungible-pausable/test_snapshots/test/burn_works.1.json
  examples/fungible-pausable/test_snapshots/test/initial_state.1.json
  examples/fungible-pausable/test_snapshots/test/mint_fails_when_paused.1.json
  examples/fungible-pausable/test_snapshots/test/mint_works.1.json
  examples/fungible-pausable/test_snapshots/test/transfer_fails_when_paused.1.json
  examples/fungible-pausable/test_snapshots/test/transfer_from_fails_when_paused.1.json
  examples/fungible-pausable/test_snapshots/test/transfer_from_works.1.json
  examples/fungible-pausable/test_snapshots/test/transfer_works.1.json
  examples/pausable/test_snapshots/test/errors_increment_when_paused.1.json
  examples/pausable/test_snapshots/test/errors_unpause_unauthorized.1.json
  examples/pausable/test_snapshots/test/initial_state.1.json
  examples/pausable/test_snapshots/test/pause_works.1.json
  examples/pausable/test_snapshots/test/unpause_works.1.json
Labels: audit

#73 [N-07] - Code Inconsistencies
  contracts/token/fungible/src/extensions/burnable/mod.rs
  contracts/token/fungible/src/extensions/burnable/storage.rs
  contracts/token/fungible/src/extensions/metadata/storage.rs
  contracts/token/fungible/src/extensions/mintable/mod.rs
  contracts/token/fungible/src/fungible.rs
  contracts/token/fungible/src/storage.rs
  contracts/utils/pausable/src/storage.rs
  docs/modules/ROOT/pages/tokens/fungible.adoc
  examples/fungible-pausable/src/contract.rs
  examples/fungible-token-interface/src/contract.rs
  examples/pausable/src/contract.rs
Labels: audit

#65 switch to stable rust
  .github/workflows/generic.yml
  rust-toolchain.toml
Labels: devops

#85 add external doc link
  README.md
  contracts/token/fungible/src/extensions/capped/storage.rs
Labels: documentation
